"""Initial migration

Revision ID: 9043214a30b0
Revises: 
Create Date: 2025-10-28 22:19:27.475799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9043214a30b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_verifications_email'), ['email'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('university_name', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('contact_no', sa.String(length=20), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('conferences',
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('hosting_university', sa.String(length=200), nullable=False),
    sa.Column('hosting_department', sa.String(length=200), nullable=False),
    sa.Column('final_schedule_file', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('author_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('participant_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('conference_id')
    )
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conferences_created_by_admin_id'), ['created_by_admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conferences_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_conferences_hosting_department'), ['hosting_department'], unique=False)
        batch_op.create_index(batch_op.f('ix_conferences_hosting_university'), ['hosting_university'], unique=False)
        batch_op.create_index(batch_op.f('ix_conferences_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_conferences_title'), ['title'], unique=False)

    op.create_table('conference_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('participant', 'author', 'reviewer', 'organizer', 'admin', name='userrole'), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('expertise', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.conference_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'conference_id', name='_user_conference_uc')
    )
    with op.batch_alter_table('conference_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conference_roles_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_conference_roles_status'), ['status'], unique=False)

    op.create_table('tracks',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.conference_id'], ),
    sa.PrimaryKeyConstraint('track_id')
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracks_conference_id'), ['conference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracks_name'), ['name'], unique=False)

    op.create_table('certificates',
    sa.Column('certificate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('certificate_type', sa.Enum('author', 'participant', 'reviewer', name='certificatetype'), nullable=False),
    sa.Column('file_path', sa.String(length=200), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['conference_roles.id'], ),
    sa.PrimaryKeyConstraint('certificate_id')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificates_certificate_type'), ['certificate_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_role_id'), ['role_id'], unique=False)

    op.create_table('papers',
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('author_role_id', sa.Integer(), nullable=False),
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('keywords', sa.String(length=250), nullable=True),
    sa.Column('blind_paper_file', sa.String(length=200), nullable=False),
    sa.Column('camera_ready_file', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'under_review', 'accepted', 'rejected', 'revision_required', name='paperstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_role_id'], ['conference_roles.id'], ),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.conference_id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ),
    sa.PrimaryKeyConstraint('paper_id')
    )
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_papers_author_role_id'), ['author_role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_papers_conference_id'), ['conference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_papers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_papers_title'), ['title'], unique=False)

    op.create_table('registrations',
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'completed', 'failed', name='paymentstatus'), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.conference_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['conference_roles.id'], ),
    sa.PrimaryKeyConstraint('registration_id')
    )
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registrations_conference_id'), ['conference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_role_id'), ['role_id'], unique=True)

    op.create_table('sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('schedule_time', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('session_chair_role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.conference_id'], ),
    sa.ForeignKeyConstraint(['session_chair_role_id'], ['conference_roles.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_conference_id'), ['conference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_schedule_time'), ['schedule_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_session_chair_role_id'), ['session_chair_role_id'], unique=False)

    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_role_id', sa.Integer(), nullable=False),
    sa.Column('comments_to_author', sa.Text(), nullable=True),
    sa.Column('comments_to_organiser', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.Enum('accept', 'reject', 'revision_required', name='reviewrecommendation'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.ForeignKeyConstraint(['reviewer_role_id'], ['conference_roles.id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_reviewer_role_id'), ['reviewer_role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_score'), ['score'], unique=False)

    op.create_table('session_papers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('presenter_role_id', sa.Integer(), nullable=False),
    sa.Column('presentation_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.ForeignKeyConstraint(['presenter_role_id'], ['conference_roles.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id')
    )
    with op.batch_alter_table('session_papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_papers_presentation_time'), ['presentation_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_papers_presenter_role_id'), ['presenter_role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_papers_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_papers_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_papers_presenter_role_id'))
        batch_op.drop_index(batch_op.f('ix_session_papers_presentation_time'))

    op.drop_table('session_papers')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_score'))
        batch_op.drop_index(batch_op.f('ix_reviews_reviewer_role_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_paper_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_session_chair_role_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_schedule_time'))
        batch_op.drop_index(batch_op.f('ix_sessions_name'))
        batch_op.drop_index(batch_op.f('ix_sessions_conference_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registrations_role_id'))
        batch_op.drop_index(batch_op.f('ix_registrations_payment_status'))
        batch_op.drop_index(batch_op.f('ix_registrations_conference_id'))

    op.drop_table('registrations')
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_papers_title'))
        batch_op.drop_index(batch_op.f('ix_papers_status'))
        batch_op.drop_index(batch_op.f('ix_papers_conference_id'))
        batch_op.drop_index(batch_op.f('ix_papers_author_role_id'))

    op.drop_table('papers')
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificates_role_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_certificate_type'))

    op.drop_table('certificates')
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_name'))
        batch_op.drop_index(batch_op.f('ix_tracks_conference_id'))

    op.drop_table('tracks')
    with op.batch_alter_table('conference_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conference_roles_status'))
        batch_op.drop_index(batch_op.f('ix_conference_roles_role'))

    op.drop_table('conference_roles')
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conferences_title'))
        batch_op.drop_index(batch_op.f('ix_conferences_start_date'))
        batch_op.drop_index(batch_op.f('ix_conferences_hosting_university'))
        batch_op.drop_index(batch_op.f('ix_conferences_hosting_department'))
        batch_op.drop_index(batch_op.f('ix_conferences_end_date'))
        batch_op.drop_index(batch_op.f('ix_conferences_created_by_admin_id'))

    op.drop_table('conferences')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('otp_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_verifications_email'))

    op.drop_table('otp_verifications')
    # ### end Alembic commands ###
